### ISSUE TITLE
Small error in the text, ecc 2.4 channels are 1-11

### ISSUE THREAD

**Issue by Damme** [mavic-mini-ce-boost/mavic-mini-ce-boost.github.io#1]
Hello and thanks for this page, it was useful for me with DJI mini (1) on android.

I noticed a small error in the text:
"There you should see that frequency is now 5.8 and the chart below displays WiFi channels 1..13 and 149..165"

CE channels are 1-13, ECC are 1-11.

Best regards
Daniel

**Comment by sergiks** [comment]
Hi @Damme ,

as I shown in the video, I set country to Bolivia and got channels 1..13.  What do you mean by "ECC" ?

**Comment by Damme** [comment]
Aaah, I didnt realize BO had 1-13 with the higher transmit power.
I mean US with ECC. I cannot find the source for that now though.

**Comment by sergiks** [comment]
Seems that for DJI Mavic Mini (1st) "CE" (Central European) version, available 2.4 GHz channels in Bolivia and in USA slightly differs: `1..11` in the USA, `1..13` in Bolivia.

That does not affect overall performance much, as the main goal is to make 5.8 GHz channels available — those with numbers above 100.
